// Code Generated by "build.go buildinfo"  DO NOT EDIT.
package main

const (
	// VERSION is the version of peg
	VERSION   = "unknown"
	// BUILDTIME is the build time of peg
	BUILDTIME = "2021-01-22T16:14:52"
	// COMMIT is the commit hash of peg
	COMMIT    = "e7588a89197f28bc2191a42a0562d77b257e20fe"
	// IS_TAGGED is there a version
	IS_TAGGED = false
)
