// Code Generated by "build.go buildinfo"  DO NOT EDIT.
package main

const (
	// VERSION is the version of peg
	VERSION   = "unknown"
	// BUILDTIME is the build time of peg
	BUILDTIME = "2021-01-24T02:46:47"
	// COMMIT is the commit hash of peg
	COMMIT    = "85b56f53a1e9a98682bafa2fb27da70191f8da9f"
	// IS_TAGGED is there a version
	IS_TAGGED = false
)
