// Code Generated by "build.go buildinfo"  DO NOT EDIT.
package main

const (
	// VERSION is the version of peg
	VERSION   = "unknown"
	// BUILDTIME is the build time of peg
	BUILDTIME = "2021-01-23T07:24:22"
	// COMMIT is the commit hash of peg
	COMMIT    = "544a89f9cd8839d522297c25d9882825063a6b18"
	// IS_TAGGED is there a version
	IS_TAGGED = false
)
